---
title: "Joshua Arford's Resume"
---

Joshua Arford



##EDUCATION

**Appalachian State University, Boone, NC August 2018 -	May 2020**

* Bachelor of Science in Mathematics 

* Major: Mathematics

* Concentration: Business

* GPA: 3.15


**Asheville-Buncombe Technical Community College May 2017- May 2018**

* Associate in Arts 

* GPA: 3.42
	

##RESEARCH EXPERIENCE

**Appalachian State University, NC	August 2018 - Present**

*Student*

* Conduct research in modular arithmetic and music theory with peers in similar degrees

* Propose bi-annual presentations to display progression of research development over time



##INVOLVEMENT

**S-STEM Program	August 2018 - Present**

*Member*

* Attend weekly seminars with fellow S-STEM scholars, including leadership workshops and

lectures given by highly accredited researchers in STEM fields

* Participate in bi-weekly study halls in order to accomplish academic goals


##VOLUNTEER EXPERIENCE 	

**Adopt-a-Stream, Canton, NC	October 2017**

*Volunteer*	

* Assisted Tom Anspach with Adopt-a-Stream waterway cleanup in the Pigeon River

* Decontaminated the river from more than 50 pounds of waste using canoes and kayaks 


**The Open Door Ministries, Waynesville, NC                                 December 2015 -February 2016**

*Volunteer*

* Provided homemade meals for hundreds of homeless citizens in the Waynesville area

* Contributed in almost  a dozen sessions by cooking, cleaning and serving at the shelter


